### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by eat-sleep-code** [schoolpost/CinePI#1]
Csaba --

I have been following your video examples on the Pi Forums and would love to incorporate your video capture logic into my own [camera program](https://github.com/eat-sleep-code/camera) (which has on screen controls, etc.).

I am currently printing Gen 3 of my camera which has a 5" hinged capacitive touch screen, top handle, multiple cold shoe mount screws, active cooling, and room for up to a 20,000mah battery.

**Comment by schoolpost** [comment]
Check the releases section, just released the first alpha version. a lot of it is explained there.

**Comment by peternewman** [comment]
Hi @schoolpost ,

On the latest release it says:

> source code will be available in the main repository. Due to the layers / complexity of creating a "Camera" through a traditional Operating system not every component of the software can be/will be referenced in the source. Filesystem drivers, boot configurations, etc.. are all examples of the additional layers that are required to make a functional camera and these layers will be left partially obfuscated from the source to reduce the number of dependencies and shear overall size of the code base. These components will be mentioned in documentation to give users the knowledge of their existence and how they can be modified/used.

Where is say the Python bmdproxy script currently being developed or the source code managed? What would someone open a pull request against if they wanted to make a change? I'm just curious about it, so don't want to have to download a 2GB file and flash it to a Pi or possibly mount it as loopback just to have a look at a few hundred kB of Python.
