### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by Stokestack** [schoolpost/CinePI#12]
Hi. I'd like to experiment with (and potentially contribute to) this project, but I don't see the source here. Just some docs and 3-D models.

Am I overlooking it? Thanks!

**Comment by schoolpost** [comment]
Hi, you will need to flash a mciro-sd with the lastest image ( found in the releases section of the github repo ) from there you will find all the source in the home directory. 

This project relies on some kernel / system level modifications and additions that I haven't yet found a way to incorporate into a traditional github package. 

That being said, I'll look into adding the core source files into the repo soon.

**Comment by Stokestack** [comment]
Thanks for the info!
