### ISSUE TITLE
Start4x.elf compatibility

### ISSUE THREAD

**Issue by origilad** [schoolpost/CinePI#15]
Hi - relatively new pi user

I downloaded your latest release - flashed onto an sd card and booted up my Raspberry Pi 4 Model B - 8GB
On boot I get the error:
```start4x.elf: is not compatible```

I tried to debug on my own and updated all the files on the sd card with files from here: https://github.com/raspberrypi/firmware/tree/master/boot
(I think this is where I went wrong^)

Doing caused the pi to start booting - the CinePi splash screen would show for a couple of seconds and then crash and open a terminal. Seems like the camera wasn't detected by the OS. 

Running ```vcgencmd get_camera``` or manually running raspistill both pointed to the camera not being detected.

I verified that the hardware/camera works - was able to run raspistill on the recommended Raspberry Pi OS.

Any ideas on what I should do?

**Comment by schoolpost** [comment]
Hello,

I would recommend you try re-flashing, perhaps with a different sd card, or try with a different flashing utility. 

Also try the first release of the firmware and see if that changes anything.

**Comment by Tiramisioux** [comment]
Hi! I have the same problem. Seems to be an issue with newer Raspberry Pi:s. Error shows up on my newly bought RPi4. On my my older the CinePi system works fine.

Found this thread: [https://forums.raspberrypi.com/viewtopic.php?t=282764](https://forums.raspberrypi.com/viewtopic.php?t=282764) and tried using the SD card in an older RPi, doing 
```
sudo apt update
sudo apt full-upgrade
```
and then move it to the new RPi4. Got the same result as @origilad, with the Pi booting, showing splash screen and crashing into terminal. In the list of "OKs", it says:

_[FAILED] Failed to start Load Kernel Modules
See systemctl 'status system-modules-load.service' for details_

**Comment by schoolpost** [comment]
> 

Thanks for looking into this, I will look into solutions.

**Comment by chapop** [comment]
Hi, i have the same problem. Perhaps a new release of Cinepi with a more recent OS compatible with the last raspberry firmware could solve it?
Unfortunately i don't know how to do that, is it possible?

**Comment by Tiramisioux** [comment]
Also had problems installing the 32-bit version of Rasbian o on my new Pi 4. 64-bit version worked fine though. Maybe this has something to do with it?

**Comment by Polyrhythm** [comment]
I also am hitting this problem with a new Raspberry Pi 4B 8gb, newly setup.
Flashed using the recommended app for OSX.

**Comment by schoolpost** [comment]
> I also am hitting this problem with a new Raspberry Pi 4B 8gb, newly setup. Flashed using the recommended app for OSX.

Noticed on the Raspberry Pi Forums you were able to resolve the issue, I'm sure those who may run into this issue in the future would appreciate knowing how to work around this If you are willing to share.

**Comment by Polyrhythm** [comment]
Yep! I did manage to resolve this with my newer Raspberry Pi 4B board.
@origilad, you were close with your thinking, but instead of copying _all_ the files from that boot folder, what you want to do is just copy over anything that starts with `fixup` or `start`. Replacing the other files is unnecessary.

Somebody else on the forum suggested that perhaps even that is unnecessary and only `fixup4_` and `start4_` files are necessary, but at this point I am just happy it boots so I didn't bother to continuously experiment to see what the minimal solution was.

Once you do that, you should have no problems starting up CinePi.

**Comment by Tiramisioux** [comment]
Can confirm that only files `fixup4_` and `start4_` (8 files total) need to be replaced for fix to work.
