### ISSUE TITLE
Unrecognized external SSD

### ISSUE THREAD

**Issue by jineshkunj** [schoolpost/CinePI#5]
Hello, thank you for making Cinepi 
Please bear with me that my mother tongue is not English.

I cannot be identified successfully when I use both SSDs
One is Samsung T5 500g, the other is Lexar 500g
It should all be usb 3.1 specifications.

But I don't know why, the SSD cannot be recognized.
Excuse me, how can I solve this problem
Thank you very much, thank you :)

**Comment by schoolpost** [comment]
> Hello, thank you for making Cinepi 
> 
> Please bear with me that my mother tongue is not English.
> 
> 
> 
> I cannot be identified successfully when I use both SSDs
> 
> One is Samsung T5 500g, the other is Lexar 500g
> 
> It should all be usb 3.1 specifications.
> 
> 
> 
> But I don't know why, the SSD cannot be recognized.
> 
> Excuse me, how can I solve this problem
> 
> Thank you very much, thank you :)

When you format the SSD make sure the volume name is "RAW" otherwise it will not be mounted.

This will be changed in a later version so it can be anything.
