### ISSUE TITLE
Running python script alongside CinePi

### ISSUE THREAD

**Issue by Tiramisioux** [schoolpost/CinePI#6]
What would be the best (and least intrusive) way to autostart and run a Python script of your own alongside CinePi? Have tried the normal ways of autostarting a script but can't get it to work.

**Comment by schoolpost** [comment]
You can look into making your script run as a service? https://websofttechs.com/tutorials/how-to-setup-python-script-autorun-in-ubuntu-18-04/

Make it run on startup.

**Comment by Tiramisioux** [comment]
Tried it out but can't seem to make it work. Could it be a permission issue, as explained here?
https://superuser.com/questions/1602999/ubuntu-systemctl-service-fails-with-main-process-exited-code-exited-status-1

**Comment by Tiramisioux** [comment]
Now it's working! Found this excellent guide [https://roboticsbackend.com/make-a-raspberry-pi-3-program-start-on-boot/](url)
