### ISSUE TITLE
Lower ISO values than 100

### ISSUE THREAD

**Issue by Tiramisioux** [schoolpost/CinePI#7]
Is it possible to add lower ISO values to the available ones? Would like to try values 6,12 and 50. Can it be done solely in proxy.py, or do I have to manipulate other files as well?

**Comment by schoolpost** [comment]
> Is it possible to add lower ISO values to the available ones? Would like to try values 6,12 and 50. Can it be done solely in proxy.py, or do I have to manipulate other files as well?

ISO, like many of the other controls is a computed value. If you wish to control it at the lowest level, ISO in this case would be the analouge_gain setting that is exposed by the V4L2 camera component. If my memory is correct, with the current way ISO is computed; 100 ISO is equal to 0 Analouge_gain. So 100 is the lowest ISO setting in this case. 

You can look into the _v4l2-ctl_ utility to see how you can control the camera settings directly.

Proxy.py is essentially using that utility to set/get camera settings.

**Comment by schoolpost** [comment]
This thread here may also be of some help in understanding how to control the camera through V4L2: https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=281994&p=1789990#p1789990

**Comment by Tiramisioux** [comment]
Thanks! Have been experimenting with v4l2-ctl and tried to change the multiplier in proxy.py from 100 to, for example 25 (for an ISO range of 25-556). But the camera still gives me 100 as the lowest ISO value. Am I understanding it correctly that this  could give an ISO range of 25 - 556? 

Or is the analogue_gain 0, giving a result similar to ISO 100 a limitation in the camera? That it's sensitivity can't be set to nil?

**Comment by schoolpost** [comment]
> Thanks! Have been experimenting with v4l2-ctl and tried to change the multiplier in proxy.py from 100 to, for example 25 (for an ISO range of 25-556). But the camera still gives me 100 as the lowest ISO value. Am I understanding it correctly that this could give an ISO range of 25 - 556?
> 
> Or is the analogue_gain 0, giving a result similar to ISO 100 a limitation in the camera? That it's sensitivity can't be set to nil?

If you want to change the display of the ISO on the liveview you also need to change the render.c file in the mmal_ui_render folder. in that file is a gain_to_iso function you will need to change that to reflect your own calculation of ISO. After making your changes make sure to run "make" so that it will recompile and be used on next bootup. 

At the end of the day, the implementation I have in place is my best interpretation of how to calculate ISO. 

Also read this: https://www.strollswithmydog.com/pi-hq-cam-sensor-performance/
