### ISSUE TITLE
cinePI boot on terminal

### ISSUE THREAD

**Issue by fpgasdr** [schoolpost/CinePI#8]
Hi,

I setup the hardware as user guide says, flash sd connect HQ camera, connect "RAW" ssd and boot the 32GB sd card in a raspi 4 4GB.

after the cinePI splash screen the terminal appears. tried to start the terminal with the credential you provide and launched the python camera/cameracore3.py command but syntax errors appears.

It seems something it's not working on autostart. how should I continue to debug my hardware?.

Regards,
Juli.

**Comment by schoolpost** [comment]
> Hi,
> 
> I setup the hardware as user guide says, flash sd connect HQ camera, connect "RAW" ssd and boot the 32GB sd card in a raspi 4 4GB.
> 
> after the cinePI splash screen the terminal appears. tried to start the terminal with the credential you provide and launched the python camera/cameracore3.py command but syntax errors appears.
> 
> It seems something it's not working on autostart. how should I continue to debug my hardware?.
> 
> Regards,
> Juli.

Have you verified that the camera works and the connection with camera to the PI is good? ( did you test it working before you tried CinePI? ) 

Otherwise, just in case I would possibly try to re-flash just in case something went wrong. Maybe a different sd card.

**Comment by fpgasdr** [comment]
working, no idea what happened but now reconnect and everything works and boots with video signal.

Thanks.

**Comment by schoolpost** [comment]
> working, no idea what happened but now reconnect and everything works and boots with video signal.
> 
> Thanks.

Sometimes there can be kernel panics, it's the just nature of the project right now with it being in alpha. 

Glad you got it up and running, I hope you can share some footage you film with it!

**Comment by fpgasdr** [comment]
Thanks, I will!
